

spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    # username: sa
    # password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
server:
  port: 8024